//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Telas.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CadastrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarOrcamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarOrcamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverOrcamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarOrcamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarPropostaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarPropostaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverPropostaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPropostaOperationCompleted;
        
        private System.Threading.SendOrPostCallback PegarPropostaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarItemsPropostaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Telas.Properties.Settings.Default.Telas_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CadastrarCompletedEventHandler CadastrarCompleted;
        
        /// <remarks/>
        public event AtualizarCompletedEventHandler AtualizarCompleted;
        
        /// <remarks/>
        public event RemoverCompletedEventHandler RemoverCompleted;
        
        /// <remarks/>
        public event ListarCompletedEventHandler ListarCompleted;
        
        /// <remarks/>
        public event CadastrarServicoCompletedEventHandler CadastrarServicoCompleted;
        
        /// <remarks/>
        public event AtualizarServicoCompletedEventHandler AtualizarServicoCompleted;
        
        /// <remarks/>
        public event RemoverServicoCompletedEventHandler RemoverServicoCompleted;
        
        /// <remarks/>
        public event ListarServicoCompletedEventHandler ListarServicoCompleted;
        
        /// <remarks/>
        public event CadastrarOrcamentoCompletedEventHandler CadastrarOrcamentoCompleted;
        
        /// <remarks/>
        public event AtualizarOrcamentoCompletedEventHandler AtualizarOrcamentoCompleted;
        
        /// <remarks/>
        public event RemoverOrcamentoCompletedEventHandler RemoverOrcamentoCompleted;
        
        /// <remarks/>
        public event ListarOrcamentoCompletedEventHandler ListarOrcamentoCompleted;
        
        /// <remarks/>
        public event CadastrarPropostaCompletedEventHandler CadastrarPropostaCompleted;
        
        /// <remarks/>
        public event AtualizarPropostaCompletedEventHandler AtualizarPropostaCompleted;
        
        /// <remarks/>
        public event RemoverPropostaCompletedEventHandler RemoverPropostaCompleted;
        
        /// <remarks/>
        public event ListarPropostaCompletedEventHandler ListarPropostaCompleted;
        
        /// <remarks/>
        public event PegarPropostaCompletedEventHandler PegarPropostaCompleted;
        
        /// <remarks/>
        public event ListarItemsPropostaCompletedEventHandler ListarItemsPropostaCompleted;
        
        /// <remarks/>
        public event RemoverItemCompletedEventHandler RemoverItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Cadastrar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Cadastrar(Cliente cliente) {
            this.Invoke("Cadastrar", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void CadastrarAsync(Cliente cliente) {
            this.CadastrarAsync(cliente, null);
        }
        
        /// <remarks/>
        public void CadastrarAsync(Cliente cliente, object userState) {
            if ((this.CadastrarOperationCompleted == null)) {
                this.CadastrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarOperationCompleted);
            }
            this.InvokeAsync("Cadastrar", new object[] {
                        cliente}, this.CadastrarOperationCompleted, userState);
        }
        
        private void OnCadastrarOperationCompleted(object arg) {
            if ((this.CadastrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Atualizar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Atualizar(Cliente cliente) {
            this.Invoke("Atualizar", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void AtualizarAsync(Cliente cliente) {
            this.AtualizarAsync(cliente, null);
        }
        
        /// <remarks/>
        public void AtualizarAsync(Cliente cliente, object userState) {
            if ((this.AtualizarOperationCompleted == null)) {
                this.AtualizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarOperationCompleted);
            }
            this.InvokeAsync("Atualizar", new object[] {
                        cliente}, this.AtualizarOperationCompleted, userState);
        }
        
        private void OnAtualizarOperationCompleted(object arg) {
            if ((this.AtualizarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Remover", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Remover(Cliente cliente) {
            this.Invoke("Remover", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void RemoverAsync(Cliente cliente) {
            this.RemoverAsync(cliente, null);
        }
        
        /// <remarks/>
        public void RemoverAsync(Cliente cliente, object userState) {
            if ((this.RemoverOperationCompleted == null)) {
                this.RemoverOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverOperationCompleted);
            }
            this.InvokeAsync("Remover", new object[] {
                        cliente}, this.RemoverOperationCompleted, userState);
        }
        
        private void OnRemoverOperationCompleted(object arg) {
            if ((this.RemoverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Listar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente[] Listar(Cliente cliente) {
            object[] results = this.Invoke("Listar", new object[] {
                        cliente});
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAsync(Cliente cliente) {
            this.ListarAsync(cliente, null);
        }
        
        /// <remarks/>
        public void ListarAsync(Cliente cliente, object userState) {
            if ((this.ListarOperationCompleted == null)) {
                this.ListarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarOperationCompleted);
            }
            this.InvokeAsync("Listar", new object[] {
                        cliente}, this.ListarOperationCompleted, userState);
        }
        
        private void OnListarOperationCompleted(object arg) {
            if ((this.ListarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCompleted(this, new ListarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarServico(Servico servico) {
            this.Invoke("CadastrarServico", new object[] {
                        servico});
        }
        
        /// <remarks/>
        public void CadastrarServicoAsync(Servico servico) {
            this.CadastrarServicoAsync(servico, null);
        }
        
        /// <remarks/>
        public void CadastrarServicoAsync(Servico servico, object userState) {
            if ((this.CadastrarServicoOperationCompleted == null)) {
                this.CadastrarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarServicoOperationCompleted);
            }
            this.InvokeAsync("CadastrarServico", new object[] {
                        servico}, this.CadastrarServicoOperationCompleted, userState);
        }
        
        private void OnCadastrarServicoOperationCompleted(object arg) {
            if ((this.CadastrarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AtualizarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtualizarServico(Servico servico) {
            this.Invoke("AtualizarServico", new object[] {
                        servico});
        }
        
        /// <remarks/>
        public void AtualizarServicoAsync(Servico servico) {
            this.AtualizarServicoAsync(servico, null);
        }
        
        /// <remarks/>
        public void AtualizarServicoAsync(Servico servico, object userState) {
            if ((this.AtualizarServicoOperationCompleted == null)) {
                this.AtualizarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarServicoOperationCompleted);
            }
            this.InvokeAsync("AtualizarServico", new object[] {
                        servico}, this.AtualizarServicoOperationCompleted, userState);
        }
        
        private void OnAtualizarServicoOperationCompleted(object arg) {
            if ((this.AtualizarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RemoverServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverServico(Servico servico) {
            this.Invoke("RemoverServico", new object[] {
                        servico});
        }
        
        /// <remarks/>
        public void RemoverServicoAsync(Servico servico) {
            this.RemoverServicoAsync(servico, null);
        }
        
        /// <remarks/>
        public void RemoverServicoAsync(Servico servico, object userState) {
            if ((this.RemoverServicoOperationCompleted == null)) {
                this.RemoverServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverServicoOperationCompleted);
            }
            this.InvokeAsync("RemoverServico", new object[] {
                        servico}, this.RemoverServicoOperationCompleted, userState);
        }
        
        private void OnRemoverServicoOperationCompleted(object arg) {
            if ((this.RemoverServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servico[] ListarServico(Servico servico) {
            object[] results = this.Invoke("ListarServico", new object[] {
                        servico});
            return ((Servico[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarServicoAsync(Servico servico) {
            this.ListarServicoAsync(servico, null);
        }
        
        /// <remarks/>
        public void ListarServicoAsync(Servico servico, object userState) {
            if ((this.ListarServicoOperationCompleted == null)) {
                this.ListarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarServicoOperationCompleted);
            }
            this.InvokeAsync("ListarServico", new object[] {
                        servico}, this.ListarServicoOperationCompleted, userState);
        }
        
        private void OnListarServicoOperationCompleted(object arg) {
            if ((this.ListarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarServicoCompleted(this, new ListarServicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarOrcamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarOrcamento(Orcamento orcamento) {
            this.Invoke("CadastrarOrcamento", new object[] {
                        orcamento});
        }
        
        /// <remarks/>
        public void CadastrarOrcamentoAsync(Orcamento orcamento) {
            this.CadastrarOrcamentoAsync(orcamento, null);
        }
        
        /// <remarks/>
        public void CadastrarOrcamentoAsync(Orcamento orcamento, object userState) {
            if ((this.CadastrarOrcamentoOperationCompleted == null)) {
                this.CadastrarOrcamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarOrcamentoOperationCompleted);
            }
            this.InvokeAsync("CadastrarOrcamento", new object[] {
                        orcamento}, this.CadastrarOrcamentoOperationCompleted, userState);
        }
        
        private void OnCadastrarOrcamentoOperationCompleted(object arg) {
            if ((this.CadastrarOrcamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarOrcamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AtualizarOrcamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtualizarOrcamento(Orcamento orcamento) {
            this.Invoke("AtualizarOrcamento", new object[] {
                        orcamento});
        }
        
        /// <remarks/>
        public void AtualizarOrcamentoAsync(Orcamento orcamento) {
            this.AtualizarOrcamentoAsync(orcamento, null);
        }
        
        /// <remarks/>
        public void AtualizarOrcamentoAsync(Orcamento orcamento, object userState) {
            if ((this.AtualizarOrcamentoOperationCompleted == null)) {
                this.AtualizarOrcamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarOrcamentoOperationCompleted);
            }
            this.InvokeAsync("AtualizarOrcamento", new object[] {
                        orcamento}, this.AtualizarOrcamentoOperationCompleted, userState);
        }
        
        private void OnAtualizarOrcamentoOperationCompleted(object arg) {
            if ((this.AtualizarOrcamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarOrcamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RemoverOrcamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverOrcamento(Orcamento orcamento) {
            this.Invoke("RemoverOrcamento", new object[] {
                        orcamento});
        }
        
        /// <remarks/>
        public void RemoverOrcamentoAsync(Orcamento orcamento) {
            this.RemoverOrcamentoAsync(orcamento, null);
        }
        
        /// <remarks/>
        public void RemoverOrcamentoAsync(Orcamento orcamento, object userState) {
            if ((this.RemoverOrcamentoOperationCompleted == null)) {
                this.RemoverOrcamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverOrcamentoOperationCompleted);
            }
            this.InvokeAsync("RemoverOrcamento", new object[] {
                        orcamento}, this.RemoverOrcamentoOperationCompleted, userState);
        }
        
        private void OnRemoverOrcamentoOperationCompleted(object arg) {
            if ((this.RemoverOrcamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverOrcamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarOrcamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Orcamento[] ListarOrcamento(Orcamento orcamento) {
            object[] results = this.Invoke("ListarOrcamento", new object[] {
                        orcamento});
            return ((Orcamento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarOrcamentoAsync(Orcamento orcamento) {
            this.ListarOrcamentoAsync(orcamento, null);
        }
        
        /// <remarks/>
        public void ListarOrcamentoAsync(Orcamento orcamento, object userState) {
            if ((this.ListarOrcamentoOperationCompleted == null)) {
                this.ListarOrcamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarOrcamentoOperationCompleted);
            }
            this.InvokeAsync("ListarOrcamento", new object[] {
                        orcamento}, this.ListarOrcamentoOperationCompleted, userState);
        }
        
        private void OnListarOrcamentoOperationCompleted(object arg) {
            if ((this.ListarOrcamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarOrcamentoCompleted(this, new ListarOrcamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarProposta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarProposta(Proposta proposta) {
            this.Invoke("CadastrarProposta", new object[] {
                        proposta});
        }
        
        /// <remarks/>
        public void CadastrarPropostaAsync(Proposta proposta) {
            this.CadastrarPropostaAsync(proposta, null);
        }
        
        /// <remarks/>
        public void CadastrarPropostaAsync(Proposta proposta, object userState) {
            if ((this.CadastrarPropostaOperationCompleted == null)) {
                this.CadastrarPropostaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarPropostaOperationCompleted);
            }
            this.InvokeAsync("CadastrarProposta", new object[] {
                        proposta}, this.CadastrarPropostaOperationCompleted, userState);
        }
        
        private void OnCadastrarPropostaOperationCompleted(object arg) {
            if ((this.CadastrarPropostaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarPropostaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AtualizarProposta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtualizarProposta(Proposta proposta) {
            this.Invoke("AtualizarProposta", new object[] {
                        proposta});
        }
        
        /// <remarks/>
        public void AtualizarPropostaAsync(Proposta proposta) {
            this.AtualizarPropostaAsync(proposta, null);
        }
        
        /// <remarks/>
        public void AtualizarPropostaAsync(Proposta proposta, object userState) {
            if ((this.AtualizarPropostaOperationCompleted == null)) {
                this.AtualizarPropostaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarPropostaOperationCompleted);
            }
            this.InvokeAsync("AtualizarProposta", new object[] {
                        proposta}, this.AtualizarPropostaOperationCompleted, userState);
        }
        
        private void OnAtualizarPropostaOperationCompleted(object arg) {
            if ((this.AtualizarPropostaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarPropostaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RemoverProposta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverProposta(Proposta proposta) {
            this.Invoke("RemoverProposta", new object[] {
                        proposta});
        }
        
        /// <remarks/>
        public void RemoverPropostaAsync(Proposta proposta) {
            this.RemoverPropostaAsync(proposta, null);
        }
        
        /// <remarks/>
        public void RemoverPropostaAsync(Proposta proposta, object userState) {
            if ((this.RemoverPropostaOperationCompleted == null)) {
                this.RemoverPropostaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverPropostaOperationCompleted);
            }
            this.InvokeAsync("RemoverProposta", new object[] {
                        proposta}, this.RemoverPropostaOperationCompleted, userState);
        }
        
        private void OnRemoverPropostaOperationCompleted(object arg) {
            if ((this.RemoverPropostaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverPropostaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarProposta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Proposta[] ListarProposta(Proposta proposta) {
            object[] results = this.Invoke("ListarProposta", new object[] {
                        proposta});
            return ((Proposta[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPropostaAsync(Proposta proposta) {
            this.ListarPropostaAsync(proposta, null);
        }
        
        /// <remarks/>
        public void ListarPropostaAsync(Proposta proposta, object userState) {
            if ((this.ListarPropostaOperationCompleted == null)) {
                this.ListarPropostaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPropostaOperationCompleted);
            }
            this.InvokeAsync("ListarProposta", new object[] {
                        proposta}, this.ListarPropostaOperationCompleted, userState);
        }
        
        private void OnListarPropostaOperationCompleted(object arg) {
            if ((this.ListarPropostaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPropostaCompleted(this, new ListarPropostaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/PegarProposta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Proposta PegarProposta(Proposta proposta) {
            object[] results = this.Invoke("PegarProposta", new object[] {
                        proposta});
            return ((Proposta)(results[0]));
        }
        
        /// <remarks/>
        public void PegarPropostaAsync(Proposta proposta) {
            this.PegarPropostaAsync(proposta, null);
        }
        
        /// <remarks/>
        public void PegarPropostaAsync(Proposta proposta, object userState) {
            if ((this.PegarPropostaOperationCompleted == null)) {
                this.PegarPropostaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPegarPropostaOperationCompleted);
            }
            this.InvokeAsync("PegarProposta", new object[] {
                        proposta}, this.PegarPropostaOperationCompleted, userState);
        }
        
        private void OnPegarPropostaOperationCompleted(object arg) {
            if ((this.PegarPropostaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PegarPropostaCompleted(this, new PegarPropostaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarItemsProposta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Item[] ListarItemsProposta(Proposta proposta) {
            object[] results = this.Invoke("ListarItemsProposta", new object[] {
                        proposta});
            return ((Item[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarItemsPropostaAsync(Proposta proposta) {
            this.ListarItemsPropostaAsync(proposta, null);
        }
        
        /// <remarks/>
        public void ListarItemsPropostaAsync(Proposta proposta, object userState) {
            if ((this.ListarItemsPropostaOperationCompleted == null)) {
                this.ListarItemsPropostaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarItemsPropostaOperationCompleted);
            }
            this.InvokeAsync("ListarItemsProposta", new object[] {
                        proposta}, this.ListarItemsPropostaOperationCompleted, userState);
        }
        
        private void OnListarItemsPropostaOperationCompleted(object arg) {
            if ((this.ListarItemsPropostaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarItemsPropostaCompleted(this, new ListarItemsPropostaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RemoverItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverItem(Item item) {
            this.Invoke("RemoverItem", new object[] {
                        item});
        }
        
        /// <remarks/>
        public void RemoverItemAsync(Item item) {
            this.RemoverItemAsync(item, null);
        }
        
        /// <remarks/>
        public void RemoverItemAsync(Item item, object userState) {
            if ((this.RemoverItemOperationCompleted == null)) {
                this.RemoverItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverItemOperationCompleted);
            }
            this.InvokeAsync("RemoverItem", new object[] {
                        item}, this.RemoverItemOperationCompleted, userState);
        }
        
        private void OnRemoverItemOperationCompleted(object arg) {
            if ((this.RemoverItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverItemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private int cliente_idField;
        
        private string nomeField;
        
        private string emailField;
        
        private string telefoneField;
        
        /// <remarks/>
        public int Cliente_id {
            get {
                return this.cliente_idField;
            }
            set {
                this.cliente_idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Item {
        
        private int item_idField;
        
        private int quantidadeField;
        
        private float precoField;
        
        private Servico servicoField;
        
        private Proposta propostaField;
        
        private float totalField;
        
        /// <remarks/>
        public int Item_id {
            get {
                return this.item_idField;
            }
            set {
                this.item_idField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public float Preco {
            get {
                return this.precoField;
            }
            set {
                this.precoField = value;
            }
        }
        
        /// <remarks/>
        public Servico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        public Proposta Proposta {
            get {
                return this.propostaField;
            }
            set {
                this.propostaField = value;
            }
        }
        
        /// <remarks/>
        public float Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Servico {
        
        private int servico_idField;
        
        private string tituloField;
        
        private string descricaoField;
        
        private float precoField;
        
        /// <remarks/>
        public int Servico_id {
            get {
                return this.servico_idField;
            }
            set {
                this.servico_idField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public float Preco {
            get {
                return this.precoField;
            }
            set {
                this.precoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Proposta {
        
        private int proposta_idField;
        
        private string tituloField;
        
        private Orcamento orcamentoField;
        
        private Item[] itemsField;
        
        /// <remarks/>
        public int Proposta_id {
            get {
                return this.proposta_idField;
            }
            set {
                this.proposta_idField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public Orcamento Orcamento {
            get {
                return this.orcamentoField;
            }
            set {
                this.orcamentoField = value;
            }
        }
        
        /// <remarks/>
        public Item[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Orcamento {
        
        private int orcamento_idField;
        
        private string descricaoField;
        
        private Cliente clienteField;
        
        private int situacaoField;
        
        private string observacaoField;
        
        /// <remarks/>
        public int Orcamento_id {
            get {
                return this.orcamento_idField;
            }
            set {
                this.orcamento_idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public int Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CadastrarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AtualizarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RemoverCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarCompletedEventHandler(object sender, ListarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CadastrarServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AtualizarServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RemoverServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarServicoCompletedEventHandler(object sender, ListarServicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CadastrarOrcamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AtualizarOrcamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RemoverOrcamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarOrcamentoCompletedEventHandler(object sender, ListarOrcamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarOrcamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarOrcamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Orcamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Orcamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CadastrarPropostaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AtualizarPropostaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RemoverPropostaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarPropostaCompletedEventHandler(object sender, ListarPropostaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPropostaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPropostaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Proposta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Proposta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PegarPropostaCompletedEventHandler(object sender, PegarPropostaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PegarPropostaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PegarPropostaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Proposta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Proposta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarItemsPropostaCompletedEventHandler(object sender, ListarItemsPropostaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarItemsPropostaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarItemsPropostaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Item[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Item[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RemoverItemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591